/**
 * Estimate ↔ Shipment correlation utility.
 *
 * Matches shipping estimates to the shipments they generated by comparing
 * address details, service type, and chronological order. This gives
 * admins a clear view of which estimates converted into shipments.
 */

import type { AdminShipment, AdminLead } from "@/types/admin-user-resources";

/**
 * Checks whether two locations share the same city and country code.
 *
 * @param a - First location (city + countryCode).
 * @param b - Second location (city + countryCode).
 * @returns `true` if city and country match (case-insensitive).
 */
function locationsMatch(
  a: { city: string; countryCode: string },
  b: { city: string; countryCode: string },
): boolean {
  return (
    a.city.toLowerCase() === b.city.toLowerCase() &&
    a.countryCode.toUpperCase() === b.countryCode.toUpperCase()
  );
}

/**
 * Finds the shipment that was most likely created from a given estimate.
 *
 * Matching criteria (all must be true):
 * 1. Shipment was created at or after the estimate.
 * 2. Pickup city + country match.
 * 3. Dropoff city + country match.
 * 4. The shipment's `serviceType` appears in one of the estimate's rates.
 *
 * When multiple shipments match, the one created closest in time to
 * the estimate is returned (most likely the direct conversion).
 *
 * @param estimate - The estimate to look up.
 * @param shipments - Pool of shipments to search through.
 * @returns The matching shipment, or `null` if no match is found.
 */
export function findShipmentForEstimate(
  estimate: AdminLead,
  shipments: AdminShipment[],
): AdminShipment | null {
  // Priority 1: Check for direct ID link (Backend correlation)
  const linkedShipment = shipments.find((s) => s.estimateId === estimate.id);
  if (linkedShipment) return linkedShipment;

  const estimateDate = new Date(estimate.createdAt).getTime();
  const rateServiceTypes = new Set(
    estimate.rates?.map((r) => r.serviceType) ?? [],
  );

  const candidates = shipments.filter((s) => {
    const shipmentDate = new Date(s.createdAt).getTime();

    // Shipment must be created at or after the estimate
    if (shipmentDate < estimateDate) return false;

    // Pickup locations must match
    if (!locationsMatch(s.pickupAddress, estimate.pickupLocation)) return false;

    // Dropoff locations must match
    if (!locationsMatch(s.dropoffAddress, estimate.dropoffLocation))
      return false;

    // Service type must match one of the estimate rates
    if (!rateServiceTypes.has(s.serviceType)) return false;

    return true;
  });

  if (candidates.length === 0) return null;

  // Return the shipment closest in time to the estimate
  candidates.sort(
    (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
  );

  return candidates[0];
}

/**
 * Finds the estimate that most likely generated a given shipment.
 *
 * Matching criteria (all must be true):
 * 1. Estimate was created at or before the shipment.
 * 2. Pickup city + country match.
 * 3. Dropoff city + country match.
 * 4. One of the estimate's rate `serviceType`s matches the shipment's.
 *
 * When multiple estimates match, the one created closest (and before)
 * the shipment is returned (most likely the source estimate).
 *
 * @param shipment - The shipment to look up.
 * @param estimates - Pool of estimates to search through.
 * @returns The matching estimate, or `null` if no match is found.
 */
export function findEstimateForShipment(
  shipment: AdminShipment,
  estimates: AdminLead[],
): AdminLead | null {
  const shipmentDate = new Date(shipment.createdAt).getTime();

  const candidates = estimates.filter((e) => {
    const estimateDate = new Date(e.createdAt).getTime();

    // Estimate must be created at or before the shipment
    if (estimateDate > shipmentDate) return false;

    // Pickup locations must match
    if (!locationsMatch(shipment.pickupAddress, e.pickupLocation)) return false;

    // Dropoff locations must match
    if (!locationsMatch(shipment.dropoffAddress, e.dropoffLocation))
      return false;

    // One of the estimate's rates must match the shipment's service type
    const rateServiceTypes = new Set(e.rates?.map((r) => r.serviceType) ?? []);
    if (!rateServiceTypes.has(shipment.serviceType)) return false;

    return true;
  });

  if (candidates.length === 0) return null;

  // Return the estimate closest in time before the shipment (most recent match)
  candidates.sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
  );

  return candidates[0];
}
